### ISSUE TITLE
Diverging implicit expansion shapeless error for type parameterized queries

### ISSUE THREAD

**Issue by mcanlas** [tpolecat/doobie#780]
I'll preface this by saying this is probably more related to `shapeless` than `doobie`, but I wanted to see if the ergonomics were intentional. And to just find out more, I'm not sure what is happening. Compare the following:

```scala
// does not compile
class MinimalBad[A: Meta, B: Meta] {
  def bad(a: A, b: B): Update0 =
    sql"""$a $b""".update
}
```

results in

```scala
diverging implicit expansion for type doobie.util.param.Param[A :: B :: shapeless.HNil]
[error] starting with method fromMeta in object Param
[error]     sql"""$a $b""".update
```

Contrast with

```scala
object MinimalGood {
  def good[A: Meta, B: Meta](a: A, b: B): Update0 =
    sql"""$a $b""".update
}
```

What's the difference?

**Comment by mcanlas** [comment]
cc @Jacoby6000

**Comment by Jacoby6000** [comment]
That doesn't fix anything, it just defers it to the thing that calls `MinimalBad.bad`. Something weird in scala might wind up making that okay, though. I don't know how scala's implicit resolution rules.

**Comment by Jacoby6000** [comment]
Not sure if this is feasible with doobie, but I did a minimal recreation of this, and fixed it.

Minimal reproduction:
```scala
import shapeless._

trait Base[A]

trait Derived[A]

object Derived {
  implicit def fromBase[A: Base] = new Derived[A] {}
  
  implicit val hnil: Derived[HNil] = new Derived[HNil] {}
  implicit def hcons[A: Derived, B <: HList : Derived]: Derived[A :: B] = new Derived[A :: B] {}
}


class Bad[K: Base, V: Base] {
  def foo = implicitly[Derived[K :: V :: HNil]]
}
```

Fixed:
```scala
import shapeless._

trait Base[A]

trait Derived[A]

object Derived {
  implicit def fromBase[A: Base] = new Derived[A] {}
  
  implicit val hnil: Derived[HNil] = new Derived[HNil] {}
  implicit def hcons[A: Derived, B <: HList : Derived]: Derived[A :: B] = new Derived[A :: B] {}

  // this fixes the problem
  implicit def hconsFromBase[A: Base, B <: HList : Derived]: Derived[A :: B] = new Derived[A :: B] {}
}


class Bad[K: Base, V: Base] {
  def foo = implicitly[Derived[K :: V :: HNil]]
}
```

I don't know if doobie could do this, but I think it should be trivial to do so.  I'm also not sure what else this might break.  It could cause lots of ambiguous implicit problems.

**Comment by mcanlas** [comment]
See also https://stackoverflow.com/questions/48837393/scala-doobie-fragment-with-generic-type-parameter/49346003

**Comment by tpolecat** [comment]
I'm looking at this on the 0.6 branch and the problem only occurs when the context bound appears on class parameters, and not on method parameters.

```scala
scala> import doobie._, doobie.implicits._, shapeless._
import doobie._
import doobie.implicits._
import shapeless._

scala> def foo[A: Put, B: Put] = Param[A :: B :: HNil]
foo: [A, B](implicit evidence$1: doobie.Put[A], implicit evidence$2: doobie.Put[B])doobie.util.param.Param[A :: B :: shapeless.HNil]

scala> class Foo[A: Put, B: Put] { Param[A :: B :: HNil] }
<console>:20: error: diverging implicit expansion for type doobie.util.param.Param[A:: B :: shapeless.HNil]
starting with method fromPut in object Param
       class Foo[A: Put, B: Put] { Param[A :: B :: HNil] }
                                        ^
```

The fix in #782 doesn't resolve it on the 0.6.x branch. 

I see this as kind of marginal because it's bad practice to place context bounds on class parameters, so I'm not inclined to spend a huge amount of time on it.

**Comment by Jacoby6000** [comment]
Fair enough. I wouldn’t spend much time on it anyway. I only did it because
I thought it was interesting that class Params implicit priority is so
different from function implicits that something just breaks.

To fix it in 0.6, I think you’d also have to update Put and Get to use low
priority implicits. Judging by the error message, you haven’t done that for
Put.

**Comment by tpolecat** [comment]
I made the same change you did, but `s/Meta/Put` and it didn't fix the problem.

**Comment by Jacoby6000** [comment]
I'll look at it some more at some point and see if I can get it working for 0.6.x

I agree that implicits on class members are in general bad practice (it's context bounds on constructors are almost universally bad), but I'm reasonably sure I've had this issue in other situations so it might be worth fixing.

**Comment by jbaileyashe** [comment]
I ran into this same problem using 0.6.0. It didn't make sense to move the type parameters from the class. I was able to correct the error by adding the implicit argument explicitly. Thank you to @Jacoby6000 and @tpolecat for suggestions here.

FWIW, I'm using the Typelevel compiler (`2.12.4-bin-typelevel-4`).
